# Python Programming Assignment

## Practical Assignment

1. You are managing a student club and need to keep track of members and their activities.  
The user will input the details of each member, including their name, age, and the activity they participate in (e.g., Music, Sports, Art).  
You need to:  
a. Create a set of unique activities.  
b. Count how many students are enrolled in each activity.  
c. Display the names of students grouped by their activity.  
d. Allow the user to enter member details until they decide to stop.  

In [1]:
records = []

while True:
    name = input("Name: ")
    if("END" == name):
        break
    age = int(input("Age: "))
    activity = input("Activity: ")
    if("END" == activity):
        break
    records.append(dict({
        "name": name,
        "age": age,
        "activity": activity
    }))

#print(records)

activities = set()
for record in records:
    activities.add(record.get("activity"))

#print(activities)

for activity in activities:
    names = [record.get("name") for record in records if record.get("activity") == activity]
    print(activity + "(" + str(len(names)) + ")" + ": " + str(names))

Games(1): ['Gyan Prakash']
sleep(1): ['Someone else']


2. The following table shows the sale details of various laptop computers over a week @Ranchi Computers

<center>

| Company | Monday | Tuesday | Wednesday | Thursday | Friday |
|---------|--------|---------|-----------|----------|--------|
| HP      | 2      | 1       | 0         | 3        | 4      |
| Lenovo  | 3      | 4       | 5         | 0        | 2      |
| Asus    | 4      | 3       | 2         | 1        | 0      |
| Dell    | 1      | 0       | 3         | 4        | 2      |

</center>

Prices of the laptops are 40000, 45000, 60000 and 35000 respectively  
Write a python script to:  
a. Construct a NumPy array of the given data.  
b. Determine the total sale of computers on each day and append it to the array.  
c. Find the revenue received for each manufacturer and append it to the array.  
d. Construct a data frame of the final NumPy array with proper row index and
column label.  

In [2]:
import numpy as np
import pandas as pd
data = np.array([
    [2, 1, 0, 3, 4],
    [3, 4, 5, 0, 2],
    [4, 3, 2, 1, 0],
    [1, 0, 3, 4, 2]
])

print(f"Initial Array:\n {data}\n")

data = np.append(data, [0] * 5).reshape((5, 5))
for i in range(0, 4):
    for j in range(0, 5):
        data[4][j] += data[i][j]

print(f"Appending each day sale:\n {data}\n")

revenue = np.array([40000, 45000, 60000, 35000])
revenues = np.array([[0], [0], [0], [0], [0]])

for i in range(0, 4):
    for j in range(0, 5):
        revenues[i][0] += data[i][j] * revenue[i]

print("Adding Revenue by each Manufacturer:")
data = np.hstack((data, revenues))
print(data)

df = pd.DataFrame(data, columns=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Revenue"])
df.insert(loc=0, column="Company", value=["HP", "Lenovo", "Asus", "Dell", "Total Sale"])
print("\nData Frame: ")
print(df)

Initial Array:
 [[2 1 0 3 4]
 [3 4 5 0 2]
 [4 3 2 1 0]
 [1 0 3 4 2]]

Appending each day sale:
 [[ 2  1  0  3  4]
 [ 3  4  5  0  2]
 [ 4  3  2  1  0]
 [ 1  0  3  4  2]
 [10  8 10  8  8]]

Adding Revenue by each Manufacturer:
[[     2      1      0      3      4 400000]
 [     3      4      5      0      2 630000]
 [     4      3      2      1      0 600000]
 [     1      0      3      4      2 350000]
 [    10      8     10      8      8      0]]

Data Frame: 
      Company  Monday  Tuesday  Wednesday  Thursday  Friday  Revenue
0          HP       2        1          0         3       4   400000
1      Lenovo       3        4          5         0       2   630000
2        Asus       4        3          2         1       0   600000
3        Dell       1        0          3         4       2   350000
4  Total Sale      10        8         10         8       8        0


3. Use the random module of numpy to generate the sales value randomly between 0 to 6
for four companies in the ques 2 (HP, Lenovo, Asus, Dell) for 5 weekdays and perform
following tasks:  
a. Create Pandas DataFrame  
b. Calculate the total sales for each day and add it as a new row in the DataFrame  
c. Calculate the total revenue for each manufacturer (using respective prices: ₹40,000, ₹45,000, ₹55,000, and ₹35,000) and add it as a new column.  
d. Save the DataFrame to a CSV file, read it back, and display the name of the company with the best sales performance [use of idxmax() is prohibited]  
[Hint:] Select the req column by label and convert to list using tolist() method.

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame(columns=["Company", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"])
df["Company"] = ["HP", "Lenovo", "Asus", "Dell"]

for column in df.columns[1:]:
    for i, el in enumerate(df[column]):
        df[column][i] = np.random.randint(0, 7)

print(df, end="\n\n")

df = pd.concat([df, pd.DataFrame({
    "Company": ["Sales"],
    "Monday": np.sum(df["Monday"]),
    "Tuesday": np.sum(df["Tuesday"]),
    "Wednesday": np.sum(df["Wednesday"]),
    "Thursday": np.sum(df["Thursday"]),
    "Friday": np.sum(df["Friday"])
})], ignore_index=True)

print(df, end="\n\n")

df["revenue"] = [40000, 45000, 55000, 35000, 0] * np.sum(df[["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]], axis=1)

print(df, end="\n\n")

df.to_csv("./SalesData.csv")

df = pd.read_csv("./SalesData.csv")

companies = df["Company"]
revenues = df["revenue"].to_list()
maxi = revenues.index(max(revenues))
print(companies[maxi])

  Company Monday Tuesday Wednesday Thursday Friday
0      HP      5       1         2        6      2
1  Lenovo      5       4         0        4      4
2    Asus      4       6         0        0      5
3    Dell      4       5         2        6      0

  Company Monday Tuesday Wednesday Thursday Friday
0      HP      5       1         2        6      2
1  Lenovo      5       4         0        4      4
2    Asus      4       6         0        0      5
3    Dell      4       5         2        6      0
4   Sales     18      16         4       16     11

  Company Monday Tuesday Wednesday Thursday Friday   revenue
0      HP      5       1         2        6      2  640000.0
1  Lenovo      5       4         0        4      4  765000.0
2    Asus      4       6         0        0      5  825000.0
3    Dell      4       5         2        6      0  595000.0
4   Sales     18      16         4       16     11       0.0

Asus


4. Construct two numpy 2D arrays A1 and A2 of any shape set by the user at run time and the elements are randomly generated by the system. Perform the following steps  
a. Construct an array A11 by selecting all the elements of the first array (A1) that are divisible by 3 but not divisible by 4  
b. Construct another array A22 by selecting all the elements of the second array (A2) that are divisible by 2 and 3  
c. Check whether A11 and A22 are empty. Continue the process if anyone array is empty  
d. Join 1 and 2 to form a single dimensional array and construct the largest possible square matrix from it  

In [4]:
import numpy as np
import math

shape1 = tuple(int(i) for i in input("Shape of Array A1").split())
shape2 = tuple(int(i) for i in input("Shape of Array A2").split())

while True:

    A1 = np.floor(np.random.rand(*shape1) * 100)
    A2 = np.floor(np.random.rand(*shape2) * 100)

    print(A1)
    print(A2)

    A11 = []
    for row in A1:
        for el in row:
            if(el % 3 == 0 and el % 4 != 0):
                A11.append(el)
    A11 = np.array(A11)
    print("\n")
    print(A11)

    A22 = []
    for row in A2:
        for el in row:
            if(el % 3 == 0 and el % 2 == 0):
                A22.append(el)
    A22 = np.array(A22)
    print(A22)

    if(not (len(A11) == 0 or len(A22) == 0)):
        break

joined = np.concatenate((A11, A22))

print("\n" + str(joined))

n = math.floor(math.sqrt(len(joined)))
square_matrix = joined.copy()
joined.resize((n, n))
print(joined)

[[78. 80. 61. 44.]
 [64. 41. 99. 93.]]
[[56. 46. 90.]
 [32. 94. 67.]
 [15. 52. 55.]
 [80. 26. 87.]]


[78. 99. 93.]
[90.]

[78. 99. 93. 90.]
[[78. 99.]
 [93. 90.]]


5. Write a Python program that takes a start and end number as input and creates a NumPy
array of numbers in this range incremented by 1. Form a square matrix B from this
array. From B, extract two new arrays, B1 and B2, where B1 contains all prime numbers
and B2 contains non-prime numbers. Finally, create two diagonal matrices B11 and
B22, where the elements of B1 and B2 are placed on the diagonals, respectively, and
the other elements are set to zero.

In [5]:
import numpy as np
import math

def isPrime(n: int) -> bool:
    for i in range(2, n):
        if(n % i == 0):
            return False
    return True

start = int(input("Enter start number"))
end = int(input("Enter end number"))

array = np.arange(start, end) + 1
print(array)

n = math.floor(math.sqrt(len(array)))
b = array.copy()
b.resize((n, n))
print("\n" + str(b))

B1 = []
B2 = []
for row in b:
    for el in row:
        if(isPrime(el)):
            B1.append(el)
        else:
            B2.append(el)

print('\n')
print(B1)
print(B2)

B11 = np.zeros((len(B1), len(B1)))
for i in range(0, len(B1)):
    for j in range(0, len(B1)):
        if(i == j):
            B11[i][j] = B1[i]


B22 = np.zeros((len(B2), len(B2)))
for i in range(0, len(B2)):
    for j in range(0, len(B2)):
        if(i == j):
            B22[i][j] = B2[i]

print('\n')
print(B11)
print(B22)


[5 6 7 8]

[[5 6]
 [7 8]]


[5, 7]
[6, 8]


[[5. 0.]
 [0. 7.]]
[[6. 0.]
 [0. 8.]]


6. Write a python script to create a NumPy array, receiving start and end numbers from user. The array should contain elements from start to two times end, incremented by 2. Create a square matrix M from this input array. From M, using conditional logic, create two new arrays A1 and A2, consisting of elements which are divisible by a non-zero number ‘n’ (take input from user), in the first array and not divisible by ‘n’ in the second array. Create two arrays A11 and A22 where the elements of A1 and A2 respectively will be the diagonal elements and the remaining array elements will be zeros.

In [6]:
import numpy as np
import math

start = int(input("Enter start number"))
end = int(input("Enter end number"))

array = np.arange(start, end) + 1
print(array)

n = math.floor(math.sqrt(len(array)))
M = array.copy()
M.resize((n, n))
print("\n" + str(M))

A1 = []
A2 = []

n = int(input("Enter non zero number n: "))

for row in b:
    for el in row:
        if(el % n == 0):
            A1.append(el)
        else:
            A2.append(el)

print('\n')
print(A1)
print(A2)

A11 = np.zeros((len(A1), len(A1)))
for i in range(0, len(A1)):
    for j in range(0, len(A1)):
        if(i == j):
            A11[i][j] = A1[i]


A22 = np.zeros((len(A2), len(A2)))
for i in range(0, len(A2)):
    for j in range(0, len(A2)):
        if(i == j):
            A22[i][j] = A2[i]

print('\n')
print(A11)
print(A22)


[5 6 7 8]

[[5 6]
 [7 8]]


[6, 8]
[5, 7]


[[6. 0.]
 [0. 8.]]
[[5. 0.]
 [0. 7.]]


7. Write a program to construct a user defined function sort_list() to sort the strings present in the list based on their length.

In [7]:
def sort_list(strlist: list) -> list:
    for i in range(0, len(strlist)):
        for j in range(i, len(strlist)):
            if(len(strlist[j]) < len(strlist[i])):
                strlist[i], strlist[j] = strlist[j], strlist[i]
    return strlist

print(sort_list(["hi", "hello", "bye"]))

['hi', 'bye', 'hello']


8. Write a program to construct a user-defined function unique_elements() that takes two
sets as input and returns a new set containing elements that are unique to each set (i.e.,
elements that are only in one of the sets and not in both).

In [8]:
def unique_elements(set1: set, set2: set) -> set:
    return set1 ^ set2

print(unique_elements({"unique 1", "unique 2", "common 1", "common 2"}, {"unique 3", "common 1", "unique 4", "common 2"}))

{'unique 4', 'unique 1', 'unique 2', 'unique 3'}


9. Create a module with name my_module to incorporate the following functions.
(minimum use of built-in functions)  
a. My_fact(): To find the factorial of all numbers that are passed in the function call. Function shall return a list of integers. (Number of elements that are passed must be of variable length)   
b. My_psq(): To find the perfect square numbers that are passed in the function call. The function shall return a list of integers. (Number of elements that are passed must be of variable length)   
c. Call both the functions from the main program and try the function call for list, set or tuple as its argument

In [9]:
# filename my_module.py (ignored because jupyter notebook, using class instead)

import math

class my_module:
    def My_fact(iterable) -> list:
        def factorial(n: int) -> int:
            if(n == 0):
                return 1
            else:
                return n * factorial(n - 1)
        return [factorial(n) for n in iterable]

    def My_psq(iterable) -> list:
        def isPerfectSquare(n: int) -> int:
            if(math.sqrt(n) == math.floor(math.sqrt(n))):
                return True
            return False            
        return [n for n in iterable if isPerfectSquare(n)]   

print(my_module.My_fact([1, 2, 3, 4, 5]))
print(my_module.My_fact({1, 2, 3, 4, 5})) 
print(my_module.My_fact((1, 2, 3, 4, 5))) 

print(my_module.My_psq([1, 2, 3, 4, 5]))
print(my_module.My_psq({1, 2, 3, 4, 5})) 
print(my_module.My_psq((1, 2, 3, 4, 5))) 



[1, 2, 6, 24, 120]
[1, 2, 6, 24, 120]
[1, 2, 6, 24, 120]
[1, 4]
[1, 4]
[1, 4]


10. Create three lists using list comprehension for 10 students  
Names:  
Roll No:  
Mid Sem Marks for Python:  


Perform following tasks:  
a. Construct a list of tuples by defining your own function my_zip  
b. Function shall check for homogeneity of all lists.  
c. Define a function my_sort for sorting the list of tuples  
d. Function shall provide keyword argument to specify parameter of sorting and to specify the type of sorting (ascending or descending)  
e. Create a data frame of the given details  
f. Add two new columns Assignment and End Sem Marks. (Generate random marks)  
g. Find the total of mid sem, end sem and assignment  
h. Add the total as a new column  
i. Convert the data frame into a csv file  

In [10]:
import pandas as pd
import numpy as np

# names = [input("Enter 10 names").split(", ")]
# roll_nos = [int(i) for i in input("Enter roll numbers: ").split()]
# mid_sem_marks = [int(m) for m in input("Enter mid sem marks: ").split()]

names = [
    "Gyan Prakash",
    "Balveer",
    "Motu",
    "Patlu",
    "Tom",
    "Jerry",
    "Thor",
    "Iron Man",
    "Optimus prime",
    "Alpha trion"
]

roll_nos = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10
]

mid_sem_marks = [29, 28, 16, 14, 26, 22, 21, 18, 22, 20]

print(names)
print(roll_nos)
print(mid_sem_marks)

def my_zip(*args):
    zip = []
    prevlen = -1
    for iterable in args:
        if(prevlen == -1):
            prevlen = len(iterable)
        elif(prevlen != len(iterable)):
            raise ValueError("Non homogeneous length of provided iterables")
    
    for i in range(prevlen):
        proto_tuple = list() # later converted to tuple
        for iterable in args:
            proto_tuple.append(iterable[i])
        proto_tuple = tuple(proto_tuple)
        zip.append(proto_tuple)

    return zip

print("\nCustom zip function: ")
custom_zip_res = my_zip(names, roll_nos, mid_sem_marks)
print(custom_zip_res)

def my_sort(iterable, keyword = 0, descending=False):
    sorted_list = list(iterable)
    for i in range(0, len(sorted_list)):
        for j in range(i, len(sorted_list)):
            if(sorted_list[j][keyword] < sorted_list[i][keyword]):
                sorted_list[i], sorted_list[j] = sorted_list[j], sorted_list[i]
    if(descending):
        return list(reversed(sorted_list))
    return sorted_list

print("\nCustom Sort: ")
print(my_sort(custom_zip_res, 0))
print(my_sort(custom_zip_res, 1))
print(my_sort(custom_zip_res, 2))
print(my_sort(custom_zip_res, 2, True))
print("\n")

df = pd.DataFrame({
    "Name": names,
    "Roll Number": roll_nos,
    "Mid Sem Marks": mid_sem_marks
})

print(df)

df["Assignment"] = np.floor(np.random.random(10) * 10)
df["End Sem Marks"] = np.floor(np.random.random(10) * 50)

print("\n" + str(df) + "\n")

df["Total Marks"] = np.sum(df[["Mid Sem Marks", "Assignment", "End Sem Marks"]], axis=1)
print(df)

df.to_csv("studentdata.csv")

['Gyan Prakash', 'Balveer', 'Motu', 'Patlu', 'Tom', 'Jerry', 'Thor', 'Iron Man', 'Optimus prime', 'Alpha trion']
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[29, 28, 16, 14, 26, 22, 21, 18, 22, 20]

Custom zip function: 
[('Gyan Prakash', 1, 29), ('Balveer', 2, 28), ('Motu', 3, 16), ('Patlu', 4, 14), ('Tom', 5, 26), ('Jerry', 6, 22), ('Thor', 7, 21), ('Iron Man', 8, 18), ('Optimus prime', 9, 22), ('Alpha trion', 10, 20)]

Custom Sort: 
[('Alpha trion', 10, 20), ('Balveer', 2, 28), ('Gyan Prakash', 1, 29), ('Iron Man', 8, 18), ('Jerry', 6, 22), ('Motu', 3, 16), ('Optimus prime', 9, 22), ('Patlu', 4, 14), ('Thor', 7, 21), ('Tom', 5, 26)]
[('Gyan Prakash', 1, 29), ('Balveer', 2, 28), ('Motu', 3, 16), ('Patlu', 4, 14), ('Tom', 5, 26), ('Jerry', 6, 22), ('Thor', 7, 21), ('Iron Man', 8, 18), ('Optimus prime', 9, 22), ('Alpha trion', 10, 20)]
[('Patlu', 4, 14), ('Motu', 3, 16), ('Iron Man', 8, 18), ('Alpha trion', 10, 20), ('Thor', 7, 21), ('Optimus prime', 9, 22), ('Jerry', 6, 22), ('Tom', 5, 26), ('Bal